/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SettingController;
import utils.ENV;
import java.awt.event.KeyEvent;
import java.awt.event.WindowListener;
import javax.swing.ButtonGroup;
import models.Setting;

/**
 *
 * @author thiennd
 */
public class SettingFrame extends javax.swing.JFrame {

    /**
     * Creates new form SettingFrame
     */
    MainMenuFrame menu;
    GetKeyDialog getKeyForm;
    ButtonGroup rbGroup;

    public void setWindowListener(WindowListener windowListener) {
        addWindowListener(windowListener);
    }

    public SettingFrame(MainMenuFrame menu) {
        setResizable(false);
        initComponents();
        this.menu = menu;
        getKeyForm = new GetKeyDialog(this);
        rbGroup = new ButtonGroup();
        rbGroup.add(rbEasy);
        rbGroup.add(rbMedium);
        rbGroup.add(rbHard);
        rbGroup.add(rbLegend);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    
    public void showControlSetting() {
        
        lbUp.setText("UP: " + KeyEvent.getKeyText(SettingController.getInstance().getKeyUp()));
        lbDown.setText("DOWN: " + KeyEvent.getKeyText(SettingController.getInstance().getKeyDown()));
        lbLeft.setText("LEFT: " + KeyEvent.getKeyText(SettingController.getInstance().getKeyLeft()));
        lbRight.setText("RIGHT: " + KeyEvent.getKeyText(SettingController.getInstance().getKeyRight()));
        lbFire.setText("FIRE: " + KeyEvent.getKeyText(SettingController.getInstance().getKeyFire()));
        lbPause.setText("PAUSE: " + KeyEvent.getKeyText(SettingController.getInstance().getKeyPause()));
        switch (SettingController.getInstance().getLevel()) {
            case Setting.EASY:
                rbGroup.setSelected(rbEasy.getModel(), true);
                break;
            case Setting.MEDIUM:
                rbGroup.setSelected(rbMedium.getModel(), true);
                break;
            case Setting.HARD:
                rbGroup.setSelected(rbHard.getModel(), true);
                break;
            case Setting.LEGEND:
                rbGroup.setSelected(rbLegend.getModel(), true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbUp = new javax.swing.JLabel();
        lbDown = new javax.swing.JLabel();
        lbLeft = new javax.swing.JLabel();
        lbRight = new javax.swing.JLabel();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbEasy = new javax.swing.JRadioButton();
        rbMedium = new javax.swing.JRadioButton();
        rbHard = new javax.swing.JRadioButton();
        rbLegend = new javax.swing.JRadioButton();
        BtnSave = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        lbFire = new javax.swing.JLabel();
        btnFire = new javax.swing.JButton();
        lbPause = new javax.swing.JLabel();
        btnPause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Control");

        lbUp.setText("Up: ");

        lbDown.setText("Down: ");

        lbLeft.setText("Left");

        lbRight.setText("Right");

        btnUp.setText("Change");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDown.setText("Change");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        btnLeft.setText("Change");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRight.setText("Change");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Level");

        rbEasy.setText("Easy");
        rbEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEasyActionPerformed(evt);
            }
        });

        rbMedium.setText("Medium");
        rbMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMediumActionPerformed(evt);
            }
        });

        rbHard.setText("Hard");
        rbHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHardActionPerformed(evt);
            }
        });

        rbLegend.setText("Legend");
        rbLegend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLegendActionPerformed(evt);
            }
        });

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        lbFire.setText("Fire");

        btnFire.setText("Change");
        btnFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFireActionPerformed(evt);
            }
        });

        lbPause.setText("Pause");

        btnPause.setText("Change");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(lbRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUp)
                            .addComponent(btnDown)
                            .addComponent(btnLeft)
                            .addComponent(btnRight))
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(rbEasy)
                            .addComponent(rbMedium)
                            .addComponent(rbHard)
                            .addComponent(rbLegend)))
                    .addComponent(btnFire)
                    .addComponent(btnPause))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUp)
                            .addComponent(btnUp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rbEasy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDown)
                    .addComponent(btnDown)
                    .addComponent(rbMedium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLeft)
                    .addComponent(btnLeft)
                    .addComponent(rbHard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRight)
                    .addComponent(btnRight)
                    .addComponent(rbLegend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFire)
                    .addComponent(btnFire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPause)
                    .addComponent(btnPause))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(BtnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        SettingController.getInstance().loadOldSetting();
        setVisible(false);
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        SettingController.getInstance().saveSetting();
        setVisible(false);
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        getKeyForm.setVisible(true, GetKeyDialog.UP);
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        getKeyForm.setVisible(true, GetKeyDialog.DOWN);
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        getKeyForm.setVisible(true, GetKeyDialog.LEFT);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        getKeyForm.setVisible(true, GetKeyDialog.RIGHT);
     }//GEN-LAST:event_btnRightActionPerformed

    private void btnFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFireActionPerformed
        getKeyForm.setVisible(true, GetKeyDialog.FIRE);
    }//GEN-LAST:event_btnFireActionPerformed

    private void rbEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEasyActionPerformed
        SettingController.getInstance().setLevel(Setting.EASY);
    }//GEN-LAST:event_rbEasyActionPerformed

    private void rbMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMediumActionPerformed
        SettingController.getInstance().setLevel(Setting.MEDIUM);
    }//GEN-LAST:event_rbMediumActionPerformed

    private void rbHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHardActionPerformed
        SettingController.getInstance().setLevel(Setting.HARD);
    }//GEN-LAST:event_rbHardActionPerformed

    private void rbLegendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLegendActionPerformed
        SettingController.getInstance().setLevel(Setting.LEGEND);
        
    }//GEN-LAST:event_rbLegendActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        getKeyForm.setVisible(true, GetKeyDialog.PAUSE);
    }//GEN-LAST:event_btnPauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnFire;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbDown;
    private javax.swing.JLabel lbFire;
    private javax.swing.JLabel lbLeft;
    private javax.swing.JLabel lbPause;
    private javax.swing.JLabel lbRight;
    private javax.swing.JLabel lbUp;
    private javax.swing.JRadioButton rbEasy;
    private javax.swing.JRadioButton rbHard;
    private javax.swing.JRadioButton rbLegend;
    private javax.swing.JRadioButton rbMedium;
    // End of variables declaration//GEN-END:variables

}
